from langchain.callbacks.base import BaseCallbackHandler
import streamlit as st

class StreamlitCallbackHandler(BaseCallbackHandler):
    def __init__(self):
        self.tokens = []

    def on_llm_new_token(self, token: str, **kwargs) -> None:
        """Display each token generated by the model in real-time."""
        self.tokens.append(token)
        # Display token in real-time on the Streamlit app
        st.write(token, end='', flush=True)
